# -*- coding: utf-8 -*-
#
# MARKUP documentation build configuration file.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

sys.path.append(os.path.abspath('../../_ext'))


# might be needed for Canny, if yes, should be here
# import jwt
# 
# canny_private_key = 'bd4601a9-32d6-8632-ac89-cd091e213c0b'
# 
# def create_canny_token(user):
#   user_data = {
#     'avatarURL': user.avatar_url, # optional but preferred
#     'email': user.email,
#     'id': user.id,
#     'name': user.name,
#   }
#   return jwt.encode(user_data, canny_private_key, algorithm='HS256')
# 


# -- General configuration -----------------------------------------------------


# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
# 
# Cannot do this just yet:
# extensions = ['sphinx.ext.todo', 'recommonmark']
# because it breaks the search when RST and MD files are in the same location by truncating a SINGLE CHARACTER from the search result link :(
extensions = ['sphinx.ext.todo', 'sphinx_design']

# autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates', '../../_templates']

# The suffix of source filenames.
source_suffix = ['.rst']

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Operators Guide'
#copyright = u''

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '0.0.1'
# The full version, including alpha/beta/rc tags.
# release = '0.0.1-1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

# highlight_language = 'ruby'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# A string of reStructuredText that will be included at the beginning of every source file that is read.
rst_prolog = """
.. include:: ../../tokens/external_links.txt
.. include:: ../../tokens/fivetran_party.txt
.. include:: ../../tokens/internal_links.txt
.. include:: ../../tokens/names.txt
"""

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'amperity'
#html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../../_themes/']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "Operators Guide"

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = "../../images/logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Path to custom CSS for sphinx-design library

html_css_files = ['sphinx-design.css']

# This setting overrides a version # stamp inserted at the bottom of every
# page. It's just a hack, but it's the hack that achieves the desired behavior.
# html_last_updated_fmt = 'current version of MARKUP documentation'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
   '**': ['localtoc.html'],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#    '404': '/internal/404.html',
html_additional_pages = {
    'add_campaigns': 'add_campaigns.html',
    'add_customer_profiles': 'add_customer_profiles.html',
    'add_data_assets': 'add_data_assets.html',
    'add_email_engagement': 'add_email_engagement.html',
    'add_predicted_models': 'add_predicted_models.html',
    'add_transactions': 'add_transactions.html',
    'api_profile': 'api_profile.html',
    'api_streaming_ingest': 'api_streaming_ingest.html',
    'blocklist_bad_values': 'blocklist_bad_values.html',
    'bridge_databricks': 'bridge_databricks.html',
    'bridge_snowflake': 'bridge_snowflake.html',
    'bridge': 'bridge.html',
    'calculate_nearest_store': 'calculate_nearest_store.html',
    'command_shell': 'command_shell.html',
    'configure_stitch': 'configure_stitch.html',
    'custom_domain_tables': 'custom_domain_tables.html',
    'data_first_party': 'data_first_party.html',
    'data_third_party': 'data_third_party.html',
    'databases': 'databases.html',
    'destination_active_campaign': 'destination_active_campaign.html',
    'destination_acxiom': 'destination_acxiom.html',
    'destination_adobe_aep': 'destination_adobe_aep.html',
    'destination_adobe_campaign': 'destination_adobe_campaign.html',
    'destination_adobe_customer_attributes': 'destination_adobe_customer_attributes.html',
    'destination_adobe_marketo': 'destination_adobe_marketo.html',
    'destination_airship': 'destination_airship.html',
    'destination_amazon_ads': 'destination_amazon_ads.html',
    'destination_amazon_pinpoint': 'destination_amazon_pinpoint.html',
    'destination_amazon_redshift': 'destination_amazon_redshift.html',
    'destination_amazon_s3': 'destination_amazon_s3.html',
    'destination_attentive_mobile_api': 'destination_attentive_mobile_api.html',
    'destination_attentive_mobile': 'destination_attentive_mobile.html',
    'destination_aws_connect': 'destination_aws_connect.html',
    'destination_azure_blob_storage': 'destination_azure_blob_storage.html',
    'destination_azure_synapse': 'destination_azure_synapse.html',
    'destination_bazaarvoice': 'destination_bazaarvoice.html',
    'destination_bluecore': 'destination_bluecore.html',
    'destination_braze': 'destination_braze.html',
    'destination_business_intelligence_connect': 'destination_business_intelligence_connect.html',
    'destination_camelot_smm': 'destination_camelot_smm.html',
    'destination_cheetah_digital': 'destination_cheetah_digital.html',
    'destination_cordial': 'destination_cordial.html',
    'destination_criteo_retail_media': 'destination_criteo_retail_media.html',
    'destination_criteo': 'destination_criteo.html',
    'destination_cross_country_computer': 'destination_cross_country_computer.html',
    'destination_domo': 'destination_domo.html',
    'destination_dv360': 'destination_dv360.html',
    'destination_dynamic_yield': 'destination_dynamic_yield.html',
    'destination_dynamics_365_marketing': 'destination_dynamics_365_marketing.html',
    'destination_epsilon_abacus': 'destination_epsilon_abacus.html',
    'destination_epsilon_conversant': 'destination_epsilon_conversant.html',
    'destination_epsilon_targeting': 'destination_epsilon_targeting.html',
    'destination_evocalize': 'destination_evocalize.html',
    'destination_experian': 'destination_experian.html',
    'destination_google_ads': 'destination_google_ads.html',
    'destination_google_bigquery': 'destination_google_bigquery.html',
    'destination_google_cloud_storage': 'destination_google_cloud_storage.html',
    'destination_google_customer_match': 'destination_google_customer_match.html',
    'destination_hubspot': 'destination_hubspot.html',
    'destination_infutor': 'destination_infutor.html',
    'destination_kibo': 'destination_kibo.html',
    'destination_klaviyo': 'destination_klaviyo.html',
    'destination_koupon_media': 'destination_koupon_media.html',
    'destination_listrak': 'destination_listrak.html',
    'destination_liveramp': 'destination_liveramp.html',
    'destination_mailchimp': 'destination_mailchimp.html',
    'destination_meta_ads_manager': 'destination_meta_ads_manager.html',
    'destination_microsoft_ads': 'destination_microsoft_ads.html',
    'destination_microsoft_dataverse': 'destination_microsoft_dataverse.html',
    'destination_microsoft_dynamics': 'destination_microsoft_dynamics.html',
    'destination_neustar': 'destination_neustar.html',
    'destination_optimizely': 'destination_optimizely.html',
    'destination_oracle_data_cloud': 'destination_oracle_data_cloud.html',
    'destination_oracle_eloqua': 'destination_oracle_eloqua.html',
    'destination_oracle_responsys': 'destination_oracle_responsys.html',
    'destination_panda_printing': 'destination_panda_printing.html',
    'destination_pebblepost': 'destination_pebblepost.html',
    'destination_persado': 'destination_persado.html',
    'destination_pinterest': 'destination_pinterest.html',
    'destination_power_bi': 'destination_power_bi.html',
    'destination_powerreviews': 'destination_powerreviews.html',
    'destination_quad': 'destination_quad.html',
    'destination_rr_donnelly': 'destination_rr_donnelly.html',
    'destination_sailthru': 'destination_sailthru.html',
    'destination_salesforce_marketing_cloud_personalization': 'destination_salesforce_marketing_cloud_personalization.html',
    'destination_salesforce_marketing_cloud': 'destination_salesforce_marketing_cloud.html',
    'destination_salesforce_sales_cloud': 'destination_salesforce_sales_cloud.html',
    'destination_sftp': 'destination_sftp.html',
    'destination_smg': 'destination_smg.html',
    'destination_snapchat': 'destination_snapchat.html',
    'destination_snowflake_aws': 'destination_snowflake_aws.html',
    'destination_snowflake_azure': 'destination_snowflake_azure.html',
    'destination_soundcommerce': 'destination_soundcommerce.html',
    'destination_tableau_amazon_redshift': 'destination_tableau_amazon_redshift.html',
    'destination_tableau_azure_synapse_analytics': 'destination_tableau_azure_synapse_analytics.html',
    'destination_tableau_databricks': 'destination_tableau_databricks.html',
    'destination_tableau_google_big_query': 'destination_tableau_google_big_query.html',
    'destination_tableau_snowflake': 'destination_tableau_snowflake.html',
    'destination_tableau': 'destination_tableau.html',
    'destination_the_trade_desk_3p': 'destination_the_trade_desk_3p.html',
    'destination_the_trade_desk': 'destination_the_trade_desk.html',
    'destination_throtle': 'destination_throtle.html',
    'destination_tiktok_ads': 'destination_tiktok_ads.html',
    'destination_tulip': 'destination_tulip.html',
    'destination_vibes': 'destination_vibes.html',
    'destination_walmart_dsp': 'destination_walmart_dsp.html',
    'destination_webhook': 'destination_webhook.html',
    'destination_yahoo_dsp': 'destination_yahoo_dsp.html',
    'destination_zendesk': 'destination_zendesk.html',
    'domain_data': 'domain_data.html',
    'events_criteo': 'events_criteo.html',
    'events_google_enhanced_conversions': 'events_google_enhanced_conversions.html',
    'events_meta_ads_manager': 'events_meta_ads_manager.html',
    'events_the_trade_desk': 'events_the_trade_desk.html',
    'events_tiktok_ads': 'events_tiktok_ads.html',
    'feeds': 'feeds.html',
    'filtered_360_databases': 'filtered_360_databases.html',
    'graph_database': 'graph_database.html',
    'historical_data': 'historical_data.html',
    'householding': 'householding.html',
    'ingest_queries': 'ingest_queries.html',
    'predict_gender': 'predict_gender.html',
    'privacy_rights': 'privacy_rights.html',
    'qa_stitch': 'qa_stitch.html',
    'qa_transactions': 'qa_transactions.html',
    'realtime': 'realtime.html',
    'sandbox_create': 'sandbox_create.html',
    'sandbox_open': 'sandbox_open.html',
    'sandbox_promote': 'sandbox_promote.html',
    'sandboxes': 'sandboxes.html',
    'semantics': 'semantics.html',
    'send_data': 'send_data.html',
    'source_acxiom': 'source_acxiom.html',
    'source_adobe_analytics': 'source_adobe_analytics.html',
    'source_adobe_campaign': 'source_adobe_campaign.html',
    'source_adobe_commerce': 'source_adobe_commerce.html',
    'source_adobe_customer_attributes': 'source_adobe_customer_attributes.html',
    'source_amazon_kinesis_data_firehose': 'source_amazon_kinesis_data_firehose.html',
    'source_amazon_s3_legacy': 'source_amazon_s3_legacy.html',
    'source_amazon_s3': 'source_amazon_s3.html',
    'source_attentive_mobile': 'source_attentive_mobile.html',
    'source_azure_blob_storage_legacy': 'source_azure_blob_storage_legacy.html',
    'source_azure_blob_storage': 'source_azure_blob_storage.html',
    'source_bazaarvoice': 'source_bazaarvoice.html',
    'source_bluecore': 'source_bluecore.html',
    'source_braze': 'source_braze.html',
    'source_camelot_smm': 'source_camelot_smm.html',
    'source_cheetah_digital': 'source_cheetah_digital.html',
    'source_cordial': 'source_cordial.html',
    'source_cross_country_computer': 'source_cross_country_computer.html',
    'source_dynamic_yield': 'source_dynamic_yield.html',
    'source_emarsys': 'source_emarsys.html',
    'source_epsilon_abacus': 'source_epsilon_abacus.html',
    'source_epsilon_conversant': 'source_epsilon_conversant.html',
    'source_epsilon_targeting': 'source_epsilon_targeting.html',
    'source_experian': 'source_experian.html',
    'source_fivetran': 'source_fivetran.html',
    'source_google_analytics': 'source_google_analytics.html',
    'source_google_cloud_storage': 'source_google_cloud_storage.html',
    'source_heap': 'source_heap.html',
    'source_hubspot': 'source_hubspot.html',
    'source_infutor': 'source_infutor.html',
    'source_klaviyo': 'source_klaviyo.html',
    'source_koupon_media': 'source_koupon_media.html',
    'source_kustomer': 'source_kustomer.html',
    'source_listrak': 'source_listrak.html',
    'source_microsoft_dataverse': 'source_microsoft_dataverse.html',
    'source_monetate': 'source_monetate.html',
    'source_neustar': 'source_neustar.html',
    'source_optimizely': 'source_optimizely.html',
    'source_oracle_data_cloud': 'source_oracle_data_cloud.html',
    'source_oracle_opera': 'source_oracle_opera.html',
    'source_oracle_responsys': 'source_oracle_responsys.html',
    'source_pebblepost': 'source_pebblepost.html',
    'source_powerreviews': 'source_powerreviews.html',
    'source_quad': 'source_quad.html',
    'source_rr_donnelly': 'source_rr_donnelly.html',
    'source_sailthru': 'source_sailthru.html',
    'source_salesforce_commerce_cloud': 'source_salesforce_commerce_cloud.html',
    'source_salesforce_marketing_cloud': 'source_salesforce_marketing_cloud.html',
    'source_salesforce_pardot': 'source_salesforce_pardot.html',
    'source_salesforce_sales_cloud': 'source_salesforce_sales_cloud.html',
    'source_sftp_amperity': 'source_sftp_amperity.html',
    'source_sftp': 'source_sftp.html',
    'source_smg': 'source_smg.html',
    'source_snowflake_aws': 'source_snowflake_aws.html',
    'source_snowflake_azure': 'source_snowflake_azure.html',
    'source_soundcommerce': 'source_soundcommerce.html',
    'source_square': 'source_square.html',
    'source_vibes': 'source_vibes.html',
    'source_zendesk': 'source_zendesk.html',
    'start_here': 'start_here.html',
    'stitch_labels': 'stitch_labels.html',
    'stitch_nicknames': 'stitch_nicknames.html',
    'stitch_qa_bad_foreign_keys': 'stitch_qa_bad_foreign_keys.html',
    'stitch_qa_cluster_scores': 'stitch_qa_cluster_scores.html',
    'stitch_qa_cluster_size_distribution': 'stitch_qa_cluster_size_distribution.html',
    'stitch_qa_combined_statistics': 'stitch_qa_combined_statistics.html',
    'stitch_qa_common_values': 'stitch_qa_common_values.html',
    'stitch_qa_connections_across_sources': 'stitch_qa_connections_across_sources.html',
    'stitch_qa_dedupe_keys_per_amperity_id': 'stitch_qa_dedupe_keys_per_amperity_id.html',
    'stitch_qa_denormalized_records': 'stitch_qa_denormalized_records.html',
    'stitch_qa_detailed_examples': 'stitch_qa_detailed_examples.html',
    'stitch_qa_fk_validation': 'stitch_qa_fk_validation.html',
    'stitch_qa_many_amperity_ids': 'stitch_qa_many_amperity_ids.html',
    'stitch_qa_many_semantic_values': 'stitch_qa_many_semantic_values.html',
    'stitch_qa_null_amperity_ids': 'stitch_qa_null_amperity_ids.html',
    'stitch_qa_queries': 'stitch_qa_queries.html',
    'stitch_qa_separated_statistics': 'stitch_qa_separated_statistics.html',
    'stitch_qa_source_cluster_distribution': 'stitch_qa_source_cluster_distribution.html',
    'stitch_qa_split_clusters': 'stitch_qa_split_clusters.html',
    'stitch_qa_unmatched_semantic_values': 'stitch_qa_unmatched_semantic_values.html',
    'stitch_qa_weakest_match': 'stitch_qa_weakest_match.html',
    'stitch_results': 'stitch_results.html',
    'stitch': 'stitch.html',
    'table_all_opted_in_emails': 'table_all_opted_in_emails.html',
    'table_campaign_recipients': 'table_campaign_recipients.html',
    'table_customer_360': 'table_customer_360.html',
    'table_customer_attributes': 'table_customer_attributes.html',
    'table_detailed_examples': 'table_detailed_examples.html',
    'table_email_ampid_assignment': 'table_email_ampid_assignment.html',
    'table_email_engagement_attributes': 'table_email_engagement_attributes.html',
    'table_email_engagement_summary': 'table_email_engagement_summary.html',
    'table_email_opt_status': 'table_email_opt_status.html',
    'table_fiscal_calendar': 'table_fiscal_calendar.html',
    'table_merged_customers': 'table_merged_customers.html',
    'table_merged_households': 'table_merged_households.html',
    'table_pii': 'table_pii.html',
    'table_predicted_affinity': 'table_predicted_affinity.html',
    'table_predicted_clv_attributes': 'table_predicted_clv_attributes.html',
    'table_sms_opt_status': 'table_sms_opt_status.html',
    'table_stitch_blocking_keys': 'table_stitch_blocking_keys.html',
    'table_stitch_blocklistvalues': 'table_stitch_blocklistvalues.html',
    'table_stitch_scores': 'table_stitch_scores.html',
    'table_transaction_attributes_extended': 'table_transaction_attributes_extended.html',
    'table_unified_changes_clusters': 'table_unified_changes_clusters.html',
    'table_unified_changes_pks': 'table_unified_changes_pks.html',
    'table_unified_coalesced': 'table_unified_coalesced.html',
    'table_unified_customers': 'table_unified_customers.html',
    'table_unified_email_events': 'table_unified_email_events.html',
    'table_unified_itemized_transactions': 'table_unified_itemized_transactions.html',
    'table_unified_loyalty_events': 'table_unified_loyalty_events.html',
    'table_unified_loyalty': 'table_unified_loyalty.html',
    'table_unified_paid_media': 'table_unified_paid_media.html',
    'table_unified_preprocessed_raw': 'table_unified_preprocessed_raw.html',
    'table_unified_product_catalog': 'table_unified_product_catalog.html',
    'table_unified_scores': 'table_unified_scores.html',
    'table_unified_transactions': 'table_unified_transactions.html',
    'validate_inputs': 'validate_inputs.html',
    'workflows': 'workflows.html',
}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sourcelink = False

# This is set to "False" because we don't want to show the default copyright, but
# do want to show the custom string defined by the "copyright" general setting (above).

html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.

# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Operators Guide'


# Edit this page on GitHub link
html_context = {
    "display_github": True, # Integrate GitHub
    "github_path": "https://github.com/amperity/amperity-docs/tree/main/amperity_datagrid/source/", # Path in the checkout to the docs root
}

