# -*- coding: utf-8 -*-
#
# MARKUP documentation build configuration file.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

sys.path.append(os.path.abspath('../../_ext'))


# might be needed for Canny, if yes, should be here
# import jwt
# 
# canny_private_key = 'bd4601a9-32d6-8632-ac89-cd091e213c0b'
# 
# def create_canny_token(user):
#   user_data = {
#     'avatarURL': user.avatar_url, # optional but preferred
#     'email': user.email,
#     'id': user.id,
#     'name': user.name,
#   }
#   return jwt.encode(user_data, canny_private_key, algorithm='HS256')
# 


# -- General configuration -----------------------------------------------------


# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
# 
# Cannot do this just yet:
# extensions = ['sphinx.ext.todo', 'recommonmark']
# because it breaks the search when RST and MD files are in the same location by truncating a SINGLE CHARACTER from the search result link :(
extensions = ['sphinx.ext.todo', 'sphinx_design']

# autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates', '../../_templates']

# The suffix of source filenames.
source_suffix = ['.rst']

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'User Guides'
#copyright = u''

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '0.0.1'
# The full version, including alpha/beta/rc tags.
# release = '0.0.1-1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

# highlight_language = 'ruby'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# A string of reStructuredText that will be included at the beginning of every source file that is read.
rst_prolog = """
.. include:: ../../tokens/external_links.txt
.. include:: ../../tokens/internal_links.txt
.. include:: ../../tokens/names.txt
"""

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'amperity'
#html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../../_themes/']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "User Guides"

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = "../../images/logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Path to custom CSS for sphinx-design library

html_css_files = ['sphinx-design.css']

# This setting overrides a version # stamp inserted at the bottom of every
# page. It's just a hack, but it's the hack that achieves the desired behavior.
# html_last_updated_fmt = 'current version of MARKUP documentation'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
   '**': ['localtoc.html'],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#    '404': '/internal/404.html',
html_additional_pages = {
    'ampiq': 'ampiq.html',
    'attribute_audience_sizes': 'attribute_audience_sizes.html',
    'attribute_average_number_of_items_intervals': 'attribute_average_number_of_items_intervals.html',
    'attribute_average_price_intervals': 'attribute_average_price_intervals.html',
    'attribute_brands_multiple': 'attribute_brands_multiple.html',
    'attribute_brands_preferred_intervals': 'attribute_brands_preferred_intervals.html',
    'attribute_brands_purchased_intervals': 'attribute_brands_purchased_intervals.html',
    'attribute_brands_purchased': 'attribute_brands_purchased.html',
    'attribute_canceled_quantity': 'attribute_canceled_quantity.html',
    'attribute_canceled_revenue': 'attribute_canceled_revenue.html',
    'attribute_channels_digital': 'attribute_channels_digital.html',
    'attribute_channels_multiple': 'attribute_channels_multiple.html',
    'attribute_channels_preferred_intervals': 'attribute_channels_preferred_intervals.html',
    'attribute_channels_purchased_intervals': 'attribute_channels_purchased_intervals.html',
    'attribute_channels_purchased': 'attribute_channels_purchased.html',
    'attribute_costs': 'attribute_costs.html',
    'attribute_currency': 'attribute_currency.html',
    'attribute_customer_profile_addresses': 'attribute_customer_profile_addresses.html',
    'attribute_customer_profile_birthdate': 'attribute_customer_profile_birthdate.html',
    'attribute_customer_profile_email': 'attribute_customer_profile_email.html',
    'attribute_customer_profile_gender': 'attribute_customer_profile_gender.html',
    'attribute_customer_profile_names': 'attribute_customer_profile_names.html',
    'attribute_customer_profile_phone': 'attribute_customer_profile_phone.html',
    'attribute_customer_ranking': 'attribute_customer_ranking.html',
    'attribute_days_since_latest_order': 'attribute_days_since_latest_order.html',
    'attribute_discount_amounts_sum_item': 'attribute_discount_amounts_sum_item.html',
    'attribute_discount_amounts_total': 'attribute_discount_amounts_total.html',
    'attribute_discount_amounts': 'attribute_discount_amounts.html',
    'attribute_discount_percents': 'attribute_discount_percents.html',
    'attribute_early_repeat_purchaser': 'attribute_early_repeat_purchaser.html',
    'attribute_first_to_latest_order': 'attribute_first_to_latest_order.html',
    'attribute_first_to_second_order': 'attribute_first_to_second_order.html',
    'attribute_is_canceled': 'attribute_is_canceled.html',
    'attribute_is_returned': 'attribute_is_returned.html',
    'attribute_list_prices': 'attribute_list_prices.html',
    'attribute_one_and_done': 'attribute_one_and_done.html',
    'attribute_order_datetimes': 'attribute_order_datetimes.html',
    'attribute_order_frequency_intervals': 'attribute_order_frequency_intervals.html',
    'attribute_order_id': 'attribute_order_id.html',
    'attribute_order_shipping_amount': 'attribute_order_shipping_amount.html',
    'attribute_order_value_average': 'attribute_order_value_average.html',
    'attribute_order_value_largest': 'attribute_order_value_largest.html',
    'attribute_payment_method': 'attribute_payment_method.html',
    'attribute_predicted_average_order_revenue': 'attribute_predicted_average_order_revenue.html',
    'attribute_predicted_clv': 'attribute_predicted_clv.html',
    'attribute_predicted_lifecycle_status': 'attribute_predicted_lifecycle_status.html',
    'attribute_predicted_order_frequency': 'attribute_predicted_order_frequency.html',
    'attribute_predicted_transactions': 'attribute_predicted_transactions.html',
    'attribute_predicted_value_tier': 'attribute_predicted_value_tier.html',
    'attribute_product_catalogs': 'attribute_product_catalogs.html',
    'attribute_profit_amounts': 'attribute_profit_amounts.html',
    'attribute_quantity': 'attribute_quantity.html',
    'attribute_repeat_365_days': 'attribute_repeat_365_days.html',
    'attribute_returned_quantity': 'attribute_returned_quantity.html',
    'attribute_returned_revenue': 'attribute_returned_revenue.html',
    'attribute_revenue_intervals': 'attribute_revenue_intervals.html',
    'attribute_revenue': 'attribute_revenue.html',
    'attribute_rfm': 'attribute_rfm.html',
    'attribute_store_id': 'attribute_store_id.html',
    'attribute_stores_preferred_intervals': 'attribute_stores_preferred_intervals.html',
    'attribute_stores_visit_intervals': 'attribute_stores_visit_intervals.html',
    'attribute_subtotals': 'attribute_subtotals.html',
    'attribute_tax_amounts': 'attribute_tax_amounts.html',
    'attribute_total_items_intervals': 'attribute_total_items_intervals.html',
    'attribute_total_items': 'attribute_total_items.html',
    'attributes': 'attributes.html',
    'campaigns_reference': 'campaigns_reference.html',
    'campaigns': 'campaigns.html',
    'channel_active_campaign': 'channel_active_campaign.html',
    'channel_adobe_marketo': 'channel_adobe_marketo.html',
    'channel_amazon_s3': 'channel_amazon_s3.html',
    'channel_attentive_mobile': 'channel_attentive_mobile.html',
    'channel_azure_blob_storage': 'channel_azure_blob_storage.html',
    'channel_braze': 'channel_braze.html',
    'channel_cheetah_digital': 'channel_cheetah_digital.html',
    'channel_cordial': 'channel_cordial.html',
    'channel_criteo': 'channel_criteo.html',
    'channel_facebook_ads': 'channel_facebook_ads.html',
    'channel_google_ads': 'channel_google_ads.html',
    'channel_google_cloud_storage': 'channel_google_cloud_storage.html',
    'channel_google_customer_match': 'channel_google_customer_match.html',
    'channel_hubspot': 'channel_hubspot.html',
    'channel_klaviyo': 'channel_klaviyo.html',
    'channel_listrak': 'channel_listrak.html',
    'channel_microsoft_ads': 'channel_microsoft_ads.html',
    'channel_sailthru': 'channel_sailthru.html',
    'channel_salesforce_marketing_cloud': 'channel_salesforce_marketing_cloud.html',
    'channel_sftp': 'channel_sftp.html',
    'channel_snapchat': 'channel_snapchat.html',
    'channel_tiktok_ads': 'channel_tiktok_ads.html',
    'churn_prevention': 'churn_prevention.html',
    'conditions_and_operators': 'conditions_and_operators.html',
    'customer_lifetime_value': 'customer_lifetime_value.html',
    'default_attributes': 'default_attributes.html',
    'destination_active_campaign': 'destination_active_campaign.html',
    'destination_adobe_marketo': 'destination_adobe_marketo.html',
    'destination_amazon_s3': 'destination_amazon_s3.html',
    'destination_attentive_mobile': 'destination_attentive_mobile.html',
    'destination_azure_blob_storage': 'destination_azure_blob_storage.html',
    'destination_braze': 'destination_braze.html',
    'destination_cheetah_digital': 'destination_cheetah_digital.html',
    'destination_cordial': 'destination_cordial.html',
    'destination_criteo_retail_media': 'destination_criteo_retail_media.html',
    'destination_criteo': 'destination_criteo.html',
    'destination_dv360': 'destination_dv360.html',
    'destination_facebook_ads': 'destination_facebook_ads.html',
    'destination_google_ads': 'destination_google_ads.html',
    'destination_google_cloud_storage': 'destination_google_cloud_storage.html',
    'destination_hubspot': 'destination_hubspot.html',
    'destination_klaviyo': 'destination_klaviyo.html',
    'destination_listrak': 'destination_listrak.html',
    'destination_liveramp': 'destination_liveramp.html',
    'destination_meta_ads_manager': 'destination_meta_ads_manager.html',
    'destination_microsoft_ads': 'destination_microsoft_ads.html',
    'destination_neustar': 'destination_neustar.html',
    'destination_oracle_eloqua': 'destination_oracle_eloqua.html',
    'destination_pinterest': 'destination_pinterest.html',
    'destination_reddit_ads': 'destination_reddit_ads.html',
    'destination_sailthru': 'destination_sailthru.html',
    'destination_salesforce_marketing_cloud': 'destination_salesforce_marketing_cloud.html',
    'destination_sftp': 'destination_sftp.html',
    'destination_snapchat': 'destination_snapchat.html',
    'destination_the_trade_desk': 'destination_the_trade_desk.html',
    'destination_tiktok_ads': 'destination_tiktok_ads.html',
    'destination_walmart_dsp': 'destination_walmart_dsp.html',
    'destination_yahoo_dsp': 'destination_yahoo_dsp.html',
    'destinations': 'destinations.html',
    'direct_mail': 'direct_mail.html',
    'events_criteo': 'events_criteo.html',
    'events_google_enhanced_conversions': 'events_google_enhanced_conversions.html',
    'events_meta_ads_manager': 'events_meta_ads_manager.html',
    'events_pinterest': 'events_pinterest.html',
    'events_snapchat': 'events_snapchat.html',
    'events_the_trade_desk': 'events_the_trade_desk.html',
    'events_tiktok_ads_manager': 'events_tiktok_ads_manager.html',
    'events': 'events.html',
    'journeys_reference': 'journeys_reference.html',
    'journeys': 'journeys.html',
    'model_event_propensity': 'model_event_propensity.html',
    'model_predicted_churn': 'model_predicted_churn.html',
    'model_predicted_clv': 'model_predicted_clv.html',
    'model_predicted_product_affinity': 'model_predicted_product_affinity.html',
    'models': 'models.html',
    'onetime_buyers': 'onetime_buyers.html',
    'paid_media': 'paid_media.html',
    'people_based_measurement': 'people_based_measurement.html',
    'purchase_behavior_first_order': 'purchase_behavior_first_order.html',
    'purchase_behavior_first_purchase': 'purchase_behavior_first_purchase.html',
    'purchase_behavior_has_not_purchased': 'purchase_behavior_has_not_purchased.html',
    'purchase_behavior_has_purchased': 'purchase_behavior_has_purchased.html',
    'purchase_behavior_most_frequent_order': 'purchase_behavior_most_frequent_order.html',
    'purchase_behavior_repeat_order': 'purchase_behavior_repeat_order.html',
    'purchase_behavior_repeat_purchase': 'purchase_behavior_repeat_purchase.html',
    'purchase_behavior_total_value_of_orders': 'purchase_behavior_total_value_of_orders.html',
    'recommended_audiences': 'recommended_audiences.html',
    'rfm': 'rfm.html',
    'segments_reference': 'segments_reference.html',
    'segments': 'segments.html',
    'standard_output': 'standard_output.html',
    'start_here': 'start_here.html',
    'usecase_1x_buyers_with_sms_optin': 'usecase_1x_buyers_with_sms_optin.html',
    'usecase_active_store_shoppers': 'usecase_active_store_shoppers.html',
    'usecase_customers_high_value_multichannel': 'usecase_customers_high_value_multichannel.html',
    'usecase_customers_high_value_new': 'usecase_customers_high_value_new.html',
    'usecase_customers_lapsing': 'usecase_customers_lapsing.html',
    'usecase_customers_top20_revenue': 'usecase_customers_top20_revenue.html',
    'usecase_customers_website_new': 'usecase_customers_website_new.html',
    'usecase_dormant_customers': 'usecase_dormant_customers.html',
    'usecase_early_repeat_purchasers': 'usecase_early_repeat_purchasers.html',
    'usecase_holiday_shoppers_sms': 'usecase_holiday_shoppers_sms.html',
    'usecase_one_and_done': 'usecase_one_and_done.html',
    'usecase_predicted_top_10_percent': 'usecase_predicted_top_10_percent.html',
    'usecase_purchased_yesterday': 'usecase_purchased_yesterday.html',
    'usecase_reduce_paid_media_spend': 'usecase_reduce_paid_media_spend.html',
    'usecase_store_invite': 'usecase_store_invite.html',
    'usecase_winback_emails_lost_customers': 'usecase_winback_emails_lost_customers.html',
}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sourcelink = False

# This is set to "False" because we don't want to show the default copyright, but
# do want to show the custom string defined by the "copyright" general setting (above).

html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.

# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'User Guides'


# Edit this page on GitHub link
html_context = {
    "display_github": True, # Integrate GitHub
    "github_path": "https://github.com/amperity/amperity-docs/tree/main/amperity_ampiq/source/", # Path in the checkout to the docs root
}
